# Isolation Forest / One Class SVM  Example

## Isolation Forest

In [4]:
# simple_example
import numpy as np
import pandas as pd
from sklearn.ensemble import IsolationForest

isolation forest의 가장 중요한 점은 contamination 비율 또한 지정가능하다.  
몇몇 대표적인 parameter에 대해 정리해보면 다음과 같다.  
- n_estimators = 나무의 개수, 디폴트 100개
- max_samples = 나무별로 몇개의 데이터를 샘플링할 것인가? 디폴트는 전체 개수와 256개중 적은 것.
- contamination = 이상치의 비율 지정 가능
- max_features = 각 나무 훈련시의 feature 개수

In [7]:
# example_1 simple one
# 15 numbers,  5 numbers strange.
X = [[-1.1], [0.3], [-7.5], [24], [1.6], 
     [1.3], [0.7], [-2.4], [-9.3], [8.5], 
     [2.0], [-2.1], [1.5], [6.7], [-0.5]]
out_clf = IsolationForest(random_state = 42, 
                          n_estimators = 10, 
                          max_samples = 10)
out_clf.fit(X)
out_clf.predict(X)
# -7.5, 24, -9.3, 8.5, 6.7  total five numbers are anormal.

array([ 1,  1, -1, -1,  1,  1,  1,  1, -1, -1,  1,  1,  1, -1,  1])

In [10]:
# example_1-1  simple one_contanimation_limit
# 15 numbers,  5 numbers strange.
X = [[-1.1], [0.3], [-7.5], [24], [1.6], 
     [1.3], [0.7], [-2.4], [-9.3], [8.5], 
     [2.0], [-2.1], [1.5], [6.7], [-0.5]]
out_clf = IsolationForest(random_state = 42, 
                          n_estimators = 10,
                          contamination = 1/5,
                          max_samples = 10)
out_clf.fit(X)
out_clf.predict(X)
# -7.5, 24, -9.3 is detected.

array([ 1,  1, -1, -1,  1,  1,  1,  1, -1,  1,  1,  1,  1,  1,  1])

## One class SVM

SVM의 방법론이 적용되어 normal와 abnormal을 구분하게 된다.
OCSVM의 경우는 data를 feature space로 mapping 이후, 분류 경계면을 통해 mapping된 data중 normal data가 원점으로부터 최대한 멀어지게 하는 것이 목적이다.

In [18]:
from sklearn.svm import OneClassSVM
X = [[-1.1], [0.3], [-7.5], [24], [1.6], 
     [1.3], [0.7], [-2.4], [-9.3], [8.5], 
     [2.0], [-2.1], [1.5], [6.7], [-0.5]]
out_clf = OneClassSVM(gamma = 'auto')
out_clf.fit(X)
out_clf.predict(X)

array([-1,  1,  1,  1,  1,  1, -1,  1, -1,  1,  1,  1,  1, -1, -1],
      dtype=int64)

앞과 다른 값들을 뱉었음을 알 수 있다.
원점과의 거리를 멀어지게 하는 최적의 조합을 찾다보니, 예상과는 다른 data에 속해진다.