<a href="https://colab.research.google.com/github/SeongwonTak/TIL_swtak/blob/master/DLBasic/IntroDLwithPytorch03_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Pytorch로 선형회귀 구현하기

In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

In [ ]:
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])

선형회귀는 가장 잘 맞는 하나의 직선을 찾는 것이다.
즉 W와 b를 찾는 것이 문제다.

In [ ]:
W = torch.zeros(1, requires_grad = True)
print(W)
b = torch.zeros(1, requires_grad = True)
print(b)

tensor([0.], requires_grad=True)
tensor([0.], requires_grad=True)


requires_grad -> 학습을 통해 계속 값이 변경되는 변수를 만든다.
따라서, 계수와 상수항 모두 그렇게 만들자.

### 가설함수 세우기

In [ ]:
hypo = x_train * W + b
print(hypo)

tensor([[0.],
        [0.],
        [0.]], grad_fn=<AddBackward0>)


### 비용 함수 선언하기
MSE를 선언하면 된다. (가설 - 평균)의 제곱 합이다.

In [ ]:
cost = torch.mean((hypo - y_train) ** 2)
print(cost)

tensor(18.6667, grad_fn=<MeanBackward0>)


In [ ]:
# optimizer 설정
optimizer = optim.SGD([W, b], lr=0.01)

nb_epochs = 1999 # 원하는만큼 경사 하강법을 반복
for epoch in range(nb_epochs + 1):

    # H(x) 계산
    hypothesis = x_train * W + b

    # cost 계산
    cost = torch.mean((hypothesis - y_train) ** 2)

    # cost로 H(x) 개선
    optimizer.zero_grad() # 매 epoch마다 미분값 초기화.
    cost.backward()
    optimizer.step()

    # 200번마다 로그 출력
    if epoch % 200 == 0:
        print('Epoch {:4d}/{} W: {:.3f}, b: {:.3f} Cost: {:.6f}'.format(
            epoch, nb_epochs, W.item(), b.item(), cost.item()
        ))

Epoch    0/1999 W: 0.187, b: 0.080 Cost: 18.666666
Epoch  200/1999 W: 1.800, b: 0.454 Cost: 0.029767
Epoch  400/1999 W: 1.876, b: 0.281 Cost: 0.011366
Epoch  600/1999 W: 1.924, b: 0.174 Cost: 0.004340
Epoch  800/1999 W: 1.953, b: 0.107 Cost: 0.001657
Epoch 1000/1999 W: 1.971, b: 0.066 Cost: 0.000633
Epoch 1200/1999 W: 1.982, b: 0.041 Cost: 0.000242
Epoch 1400/1999 W: 1.989, b: 0.025 Cost: 0.000092
Epoch 1600/1999 W: 1.993, b: 0.016 Cost: 0.000035
Epoch 1800/1999 W: 1.996, b: 0.010 Cost: 0.000013


경사하강법을 적용하였다. 이는 grad의 반대방향으로 계속 나아가, 최적점을 찾아가는 방식이다. 하지만 이를 위해서는 계속 미분을 해야하는데?

torch에서는 Autograd를 제공한다!

### Autograd

In [ ]:
### Autograd 2w^2+5를 w=2에서 미분한 값은?
w = torch.tensor(2.0, requires_grad=True)
y = w ** 2
z = 2 * y + 5
z.backward() # 기울기 호출

In [ ]:
print(w.grad)

tensor(8.)


### 다중 선형회귀 구현하기
다중 선형회귀는 변수가 여러개니, 가중치도 여러개! 간단!

In [ ]:
x1_train = torch.FloatTensor([[73], [93], [89], [96], [73]])
x2_train = torch.FloatTensor([[80], [88], [91], [98], [66]])
x3_train = torch.FloatTensor([[75], [93], [90], [100], [70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

In [ ]:
# 가중치 w와 편향 b 초기화
w1 = torch.zeros(1, requires_grad=True)
w2 = torch.zeros(1, requires_grad=True)
w3 = torch.zeros(1, requires_grad=True)
b = torch.zeros(1, requires_grad=True)

In [ ]:
# optimizer 설정
optimizer = optim.SGD([w1, w2, w3, b], lr=1e-5) # 학습률결정

nb_epochs = 1000
for epoch in range(nb_epochs + 1):

    # H(x) 계산
    hypothesis = x1_train * w1 + x2_train * w2 + x3_train * w3 + b

    # cost 계산
    cost = torch.mean((hypothesis - y_train) ** 2)

    # cost로 H(x) 개선
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    # 100번마다 로그 출력
    if epoch % 100 == 0:
        print('Epoch {:4d}/{} w1: {:.3f} w2: {:.3f} w3: {:.3f} b: {:.3f} Cost: {:.6f}'.format(
            epoch, nb_epochs, w1.item(), w2.item(), w3.item(), b.item(), cost.item()
        ))

Epoch    0/1000 w1: 0.294 w2: 0.294 w3: 0.297 b: 0.003 Cost: 29661.800781
Epoch  100/1000 w1: 0.674 w2: 0.661 w3: 0.676 b: 0.008 Cost: 1.563628
Epoch  200/1000 w1: 0.679 w2: 0.655 w3: 0.677 b: 0.008 Cost: 1.497595
Epoch  300/1000 w1: 0.684 w2: 0.649 w3: 0.677 b: 0.008 Cost: 1.435044
Epoch  400/1000 w1: 0.689 w2: 0.643 w3: 0.678 b: 0.008 Cost: 1.375726
Epoch  500/1000 w1: 0.694 w2: 0.638 w3: 0.678 b: 0.009 Cost: 1.319507
Epoch  600/1000 w1: 0.699 w2: 0.633 w3: 0.679 b: 0.009 Cost: 1.266222
Epoch  700/1000 w1: 0.704 w2: 0.627 w3: 0.679 b: 0.009 Cost: 1.215703
Epoch  800/1000 w1: 0.709 w2: 0.622 w3: 0.679 b: 0.009 Cost: 1.167810
Epoch  900/1000 w1: 0.713 w2: 0.617 w3: 0.680 b: 0.009 Cost: 1.122429
Epoch 1000/1000 w1: 0.718 w2: 0.613 w3: 0.680 b: 0.009 Cost: 1.079390


하지만 이를 행렬 연산으로도 구현 가능할 것이다.
$$H(X) = XW + B$$
의 형태로 표현 가능하다.



In [ ]:
# train set 정의
# x_train 5 * 3
# y_train 5 * 1
x_train  =  torch.FloatTensor([[73,  80,  75], 
                               [93,  88,  93], 
                               [89,  91,  80], 
                               [96,  98,  100],   
                               [73,  66,  70]])  
y_train  =  torch.FloatTensor([[152],  [185],  [180],  [196],  [142]])

In [ ]:
# 따라서  w = 3 * 1 
# 가중치와 편향 선언
W = torch.zeros((3, 1), requires_grad=True)
b = torch.zeros(1, requires_grad=True)
print(W)
print(b)

tensor([[0.],
        [0.],
        [0.]], requires_grad=True)
tensor([0.], requires_grad=True)


In [ ]:
# optimizer 설정
optimizer = optim.SGD([W, b], lr=1e-5)

nb_epochs = 20
for epoch in range(nb_epochs + 1):

    # H(x) 계산
    # 편향 b는 브로드 캐스팅되어 각 샘플에 더해집니다.
    # Matmul로 됨에 주의
    hypothesis = x_train.matmul(W) + b

    # cost 계산
    cost = torch.mean((hypothesis - y_train) ** 2)

    # cost로 H(x) 개선
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    print('Epoch {:4d}/{} hypothesis: {} Cost: {:.6f}'.format(
        epoch, nb_epochs, hypothesis.squeeze().detach(), cost.item()
    ))

Epoch    0/20 hypothesis: tensor([0., 0., 0., 0., 0.]) Cost: 29661.800781
Epoch    1/20 hypothesis: tensor([66.7178, 80.1701, 76.1025, 86.0194, 61.1565]) Cost: 9537.694336
Epoch    2/20 hypothesis: tensor([104.5421, 125.6208, 119.2478, 134.7862,  95.8280]) Cost: 3069.590088
Epoch    3/20 hypothesis: tensor([125.9858, 151.3882, 143.7087, 162.4333, 115.4844]) Cost: 990.670288
Epoch    4/20 hypothesis: tensor([138.1429, 165.9963, 157.5768, 178.1071, 126.6283]) Cost: 322.481873
Epoch    5/20 hypothesis: tensor([145.0350, 174.2780, 165.4395, 186.9928, 132.9461]) Cost: 107.717064
Epoch    6/20 hypothesis: tensor([148.9423, 178.9730, 169.8976, 192.0301, 136.5279]) Cost: 38.687496
Epoch    7/20 hypothesis: tensor([151.1574, 181.6346, 172.4254, 194.8856, 138.5585]) Cost: 16.499043
Epoch    8/20 hypothesis: tensor([152.4131, 183.1435, 173.8590, 196.5043, 139.7097]) Cost: 9.365656
Epoch    9/20 hypothesis: tensor([153.1250, 183.9988, 174.6723, 197.4217, 140.3625]) Cost: 7.071114
Epoch   10/20 hyp

## torch.nn으로 선형회귀 구현하기

In [2]:
# 데이터
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])

In [3]:
# nn.Linear는 입력의 차원, 출력의 차원을 인수로 받는다.
model = nn.Linear(1, 1)

In [4]:
# 가중치가 사전에 저장되어있다! 랜덤값으로 지정 및 자동미분화되어있다.
print(list(model.parameters()))

[Parameter containing:
tensor([[-0.6015]], requires_grad=True), Parameter containing:
tensor([-0.7731], requires_grad=True)]


In [5]:
optimizer = torch.optim.SGD(model.parameters(), lr = 0.01)

In [6]:
# 전체 훈련 데이터에 대해 경사 하강법을 2,000회 반복
nb_epochs = 2000
for epoch in range(nb_epochs+1):

    # H(x) 계산
    prediction = model(x_train)

    # cost 계산
    cost = F.mse_loss(prediction, y_train) # <== 파이토치에서 제공하는 평균 제곱 오차 함수

    # cost로 H(x) 개선하는 부분
    # gradient를 0으로 초기화
    optimizer.zero_grad()
    # 비용 함수를 미분하여 gradient 계산
    cost.backward() # backward 연산
    # W와 b를 업데이트
    optimizer.step()

    if epoch % 100 == 0:
    # 100번마다 로그 출력
      print('Epoch {:4d}/{} Cost: {:.6f}'.format(
          epoch, nb_epochs, cost.item()
      ))

Epoch    0/2000 Cost: 40.225719
Epoch  100/2000 Cost: 0.008577
Epoch  200/2000 Cost: 0.005300
Epoch  300/2000 Cost: 0.003275
Epoch  400/2000 Cost: 0.002024
Epoch  500/2000 Cost: 0.001251
Epoch  600/2000 Cost: 0.000773
Epoch  700/2000 Cost: 0.000478
Epoch  800/2000 Cost: 0.000295
Epoch  900/2000 Cost: 0.000182
Epoch 1000/2000 Cost: 0.000113
Epoch 1100/2000 Cost: 0.000070
Epoch 1200/2000 Cost: 0.000043
Epoch 1300/2000 Cost: 0.000027
Epoch 1400/2000 Cost: 0.000016
Epoch 1500/2000 Cost: 0.000010
Epoch 1600/2000 Cost: 0.000006
Epoch 1700/2000 Cost: 0.000004
Epoch 1800/2000 Cost: 0.000002
Epoch 1900/2000 Cost: 0.000001
Epoch 2000/2000 Cost: 0.000001


In [7]:
# 다중도 유사하게 진행
x_train = torch.FloatTensor([[73, 80, 75],
                             [93, 88, 93],
                             [89, 91, 90],
                             [96, 98, 100],
                             [73, 66, 70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

# 모델을 선언 및 초기화. 다중 선형 회귀이므로 input_dim=3, output_dim=1.
model = nn.Linear(3,1)

In [8]:
optimizer = torch.optim.SGD(model.parameters(), lr=1e-5) 
nb_epochs = 2000
for epoch in range(nb_epochs+1):

    # H(x) 계산
    prediction = model(x_train)
    # model(x_train)은 model.forward(x_train)와 동일함.

    # cost 계산
    cost = F.mse_loss(prediction, y_train) # <== 파이토치에서 제공하는 평균 제곱 오차 함수

    # cost로 H(x) 개선하는 부분
    # gradient를 0으로 초기화
    optimizer.zero_grad()
    # 비용 함수를 미분하여 gradient 계산
    cost.backward()
    # W와 b를 업데이트
    optimizer.step()

    if epoch % 100 == 0:
    # 100번마다 로그 출력
      print('Epoch {:4d}/{} Cost: {:.6f}'.format(
          epoch, nb_epochs, cost.item()
      ))

Epoch    0/2000 Cost: 33553.636719
Epoch  100/2000 Cost: 9.746776
Epoch  200/2000 Cost: 9.241632
Epoch  300/2000 Cost: 8.763127
Epoch  400/2000 Cost: 8.309898
Epoch  500/2000 Cost: 7.880556
Epoch  600/2000 Cost: 7.473870
Epoch  700/2000 Cost: 7.088633
Epoch  800/2000 Cost: 6.723675
Epoch  900/2000 Cost: 6.378000
Epoch 1000/2000 Cost: 6.050624
Epoch 1100/2000 Cost: 5.740456
Epoch 1200/2000 Cost: 5.446655
Epoch 1300/2000 Cost: 5.168356
Epoch 1400/2000 Cost: 4.904712
Epoch 1500/2000 Cost: 4.655000
Epoch 1600/2000 Cost: 4.418455
Epoch 1700/2000 Cost: 4.194404
Epoch 1800/2000 Cost: 3.982154
Epoch 1900/2000 Cost: 3.781089
Epoch 2000/2000 Cost: 3.590656


In [10]:
print(list(model.parameters()))

[Parameter containing:
tensor([[0.7049, 0.8929, 0.4155]], requires_grad=True), Parameter containing:
tensor([0.0586], requires_grad=True)]
