<a href="https://colab.research.google.com/github/SeongwonTak/TIL_swtak/blob/master/DLBasic/IntroDLwithPytorch02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Pytorch로 텐서 선언하기

In [1]:
import torch

In [3]:
t = torch.FloatTensor([0, 1, 2])
t

tensor([0., 1., 2.])

In [5]:
t = torch.FloatTensor([[1, 2, 3],
                       [4, 5, 6]])
t

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [6]:
print(t.dim())
print(t.size())
print(t[:, 1])

2
torch.Size([2, 3])
tensor([2., 5.])


In [7]:
# matmul vs mul
m1 = torch.FloatTensor([[1, 2],[3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print(m1.matmul(m2)) #행렬 곱셈
print(m1.mul(m2)) #스칼라 곱셈

tensor([[ 5.],
        [11.]])
tensor([[1., 2.],
        [6., 8.]])


### View (중요)
원소의 수를 유지하면서 텐서의 크기를 변경하는 방법.



In [8]:
import numpy as np

t = np.array([[[0, 1, 2],
               [3, 4, 5]],
              [[6, 7, 8],
               [9, 10, 11]]])
ft = torch.FloatTensor(t)

In [9]:
print(ft.shape)

torch.Size([2, 2, 3])


In [11]:
# 3차원에서 2차원
print(ft.view([-1, 3]))
print((ft.view([-1,3])).shape)
# -1은 아몰랑 의미, 크기 맞춰줌

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])


In [13]:
# 3차원 -> 3차원
print(ft.view([-1, 1, 3]))
print(ft.view([-1, 1, 3]).shape)

tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
torch.Size([4, 1, 3])
