<a href="https://colab.research.google.com/github/SeongwonTak/TIL_swtak/blob/master/Math/%ED%86%B5%EA%B3%84%EA%B8%B0%EC%B4%88%EC%BD%94%EB%93%9C_%EC%A0%95%EB%A6%AC.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 통계 기초 코드 정리

In [9]:
# 가장 기본
import numpy as np
import scipy as sp
import statsmodels.api as sm

/usr/local/lib/python3.7/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm


## 대표값 계산

In [12]:
a = np.array([13, 20, 15, 30, 22, 13, 15, 20, 24, 30, 35, 19, 24, 22, 26, 30])
print("평균 : %.2f" %(np.mean(a)))
print("표본중앙 : %.2f" %(np.median(a)))
print("argmax : %.2f" %(np.argmax(a))) # 최댓값 위치
# 최빈값의 경우는 조금 다름
print(sp.stats.mode(a))
# 다음과 같이 최빈값과, 그 개수가 나온다.

평균 : 22.38
표본중앙 : 22.00
argmax : 10.00
ModeResult(mode=array([30]), count=array([3]))


## 표분편차, 분산, 사분위수

In [13]:
print("분산 : %.2f" %(np.var(a)))
print("표준편차 : %.2f" %(np.std(a)))
# 사분위수 : 제1사분위 25, 제2 중간, 제3 75
print("제1사분위수 : %.2f" %(np.quantile(a, 0.25)))
print("제2사분위수 : %.2f" %(np.quantile(a, 0.5)))
print("제3사분위수 : %.2f" %(np.quantile(a, 0.75)))
# 사분위간 범위 : 제3사분위수 - 제1사분위수

분산 : 41.23
표준편차 : 6.42
제1사분위수 : 18.00
제2사분위수 : 22.00
제3사분위수 : 27.00


## 비대칭도(왜도), 첨도

왜도는 분포의 비대칭도를 나타내는 통계량.  
- 왜도가 0보다 작으면, 좌측으로 쏠린 데이터
  오른쪽으로 긴 꼬리
- 왜도가 0보다 크면, 우측으로 쏠린 데이터  
  좌측으로 긴 꼬리  

첨도는 중앙부분의 뾰족함에 대한 정보를 제공  
- 첨도가 0보다 크면, 정규분포보다 꼬리가 더 김
- 첨도가 0보다 작으면, 중앙분포에 더 집중

In [15]:
print("왜도 : %.2f" %(sp.stats.skew(a)))
print("첨도 : %.2f" %(sp.stats.kurtosis(a)))

왜도 : 0.21
첨도 : -0.89


## 공분산, 상관계수

공분산은, 두 변수가 함께 변화하는 정도를 나타내는 지표, 선형성을 측정하는 지표이다.

In [20]:
x = [-5, -2, -1, 0, 1, 2, 4]
y = [-7, -4, -3, 0, 2, 4, 5]
np.cov(x, y)
#  정확히는 공분산 행렬을 얻게 된다.
# 따라서, np.cov(x, y)[0, 1]로.

array([[ 8.47619048, 12.5952381 ],
       [12.5952381 , 19.61904762]])

In [24]:
# 상관계수 출력
print(np.corrcoef(x, y)[0, 1])

cov = np.cov(x, y)[0, 1]
xsd = np.std(x, ddof = 1)
ysd = np.std(y, ddof = 1)
print(cov / (xsd * ysd))

0.9767132226602123
0.9767132226602123


In [25]:
# 상관계수 검증법
sp.stats.pearsonr(x, y)

(0.9767132226602123, 0.00015695958076209803)

## 여러가지 확률 분포

In [27]:
# 이항분포
N = 10  # 시행횟수
mu = 0.6  # 성공 확률
rv = sp.stats.binom(N, mu)
rv

In [28]:
# 정규분포
mu = 0
std = 1
rv = sp.stats.norm(mu, std)
rv

### student t-분포
정규분포에 비해 양 끝단의 비중이 더 큰 데이터인 경우(fat- tail)  
정규분포에서 계산한 표본평균을 표본표준편차로 정규화할 경우 t-통계량

### 카이제곱분포
확률변수 X를 N개의 표본(x1, ... xN)의 합을 표본 분산으로 정규화 할 경우, 스튜던트 k-분포다.

그런데, N개의 표본들을 단순히 더하는 것이 아니라 제곱을 하며 더하면, chi-squared라고 한다.

In [ ]:
# 자유도에 따라 카이제곱분포를 주게됨.
rv = sp.stats.chi2( df = 2)

### F 분포
카이제곱 분포를 따르는 부 확률변수가 있으면, 확률 변수의 비율을 구하면 F분포가 된다.

In [30]:
# 이것의 경우는 일단 직접 구현
rv = sp.stats.norm()
M = 10000

N1 = 10
x1 = rv.rvs((N1, M))
t1 = (x1 ** 2).sum(axis=0)

N2 = 10
x2 = rv.rvs((N2, M))
t2 = (x2 ** 2).sum(axis=0)

t = t2 / t1

## 통계 검정

### 카이제곱 검정(Chi-squared Test)
카이제곱 검정이란, 범주형 확률 분포의 모수가 예측한 것과 일치하는지 보려는 검정이다. 즉 적합도 검정이다.

검정통계량
$$ \sum_{k=1}^{K}\frac{(x_{k}-m_{k})^{2}}{m_{k}}$$


- 귀무가설 : 변수들은 주어진 확률 분포를 따른다.
- 대립가설 : 변수들은 주어진 확률 분포를 따른다고 볼 수 없다.

In [31]:
# scipy.stats.chisquare(f_obs, f_exp=None)
N = 10
K = 4
mu_0 = np.ones(K)/K
np.random.seed(9)
x = np.random.choice(K, N, p=mu_0)
print(x)
n = np.bincount(x, minlength=K)
print(n)

[0 2 1 0 0 0 1 0 0 1]
[6 3 1 0]


In [32]:
sp.stats.chisquare(n)

Power_divergenceResult(statistic=8.4, pvalue=0.03842931885788852)

유의확률 5% 하에, p-val 값이 더 작으므로, 귀무가설이 기각된다.
즉, 현재 나온 x의 분포는 (0.25, 0.25, 0.25, 0.25)를 따른다고 볼 수 없다.

### 카이제곱 독립검정
이 검정은, 두 확률변수 X, Y에 대해 두 확률 변수가 독립인지 상관관계를 가지는지 검증할 수 있다.  
X와 Y가 독립이라면, 결합 확률질량함수 $P(X, Y)$는 각 확률변수 X, Y의 주변확률밀도 함수 $P(X)$, $P(Y)$의 곱이다.

그런데, 분할표가 조금 다르게  나온다면, 이것이 표본 오차에 의해서 생긴 것인지, 원래 독립이 아닌것인지 확인해봐야 한다.

- 귀무가설 : 두 변수는 독립이다.
- 대립가설 : 두 변수는 독립이 아니다.


### 단일표본 t-검정

모집단의 표준편차를 모르는 경우가 많다. 표본의 표준편차를 이용하는 경우에는, 변환된 변수는 t-분포를 따르게 된다. 이때는 t-검증을 사용하게 된다.

전제조건 : t-검정을 하는 변수는 정규분포를 따른다.
정규성 검정은 선행되어야 한다.


t-test의 가설
- 귀무가설 : 평균은 주어진 값이 맞다.
- 대립가설 : 평균은 주어진 값이 아니다.

In [33]:
# 알려진 평균
mu = 25

# 수집된 표본
data = [35,40,12,15,21,14,46,10,28,48,16,30,32,48,31,22,12,39,19,25]

sp.stats.ttest_1samp(data, mu)

Ttest_1sampResult(statistic=0.7687155636314738, pvalue=0.4515123595472501)

p-value값이 0.45로 유의수준 5% 하에서 p-val값이 더 높다. 즉 귀무가설을 기각할 수 없다.

In [34]:
np.mean(data)

27.15

### 독립표본 t-검정, 대응표본 t-검정

독립표본 t-검정 : 서로 독립적인 두 집단의 평균 비교
대응표본 t-검정 : 사전사후 비교.

독립표본 t-검정이란, 두 "독립표본"의 평균을 통계적으로 비교하는 기법이다. 



- 귀무가설 : 두 집단의 평균은 같다.
- 대립가설 : 두 집단의 평균은 다르다.


대응표본 t-검정은 서로 쌍으로 주어진 데이터에 대한 두 값의 차이를 보는 검정으로 특정 사건에 대한 효과가 있는지에 대해 중점적으로 본다.

- 귀무가설 : 효과가 없다.(평균의 차이는 0이다.)
- 대립가설 : 효과가 있다.(평균의 차이는 0이 아니다.)

귀무가설이 기각되면 두 집단 간의 차이가 유의미해질 것이다.

In [37]:
# ex - 독립표본 t검정
dat_M = [117, 108, 105, 89, 101, 93, 96, 108, 108, 94, 93, 112, 92, 91, 100, 96, 120, 86, 96, 95]
dat_F = [121, 101, 102, 114, 103, 105, 101, 131, 96, 109, 109, 113, 115, 94, 108, 96, 110, 112, 120, 100]
sp.stats.ttest_ind(dat_M, dat_F, equal_var = False)

Ttest_indResult(statistic=-2.670573872669349, pvalue=0.01108318824471652)

p-val 값이 유의수준 5% 하에서 더 작으므로, 두 집단의 평균 차이는 유의수준 5% 하에서 통계적으로 유의미하다.

### 분산분석(ANOVA)

분산분석이랑, 두 개 이상의 집단에 대해 1개의 변수에 대해 평균비교를 하는 방법이다. 분산분석의 경우는, 그룹의 수가 여러개일 때 사용한다.

분산분석의 조건
- 각 표본의 정규성
- 분산이 동일한가?
- 각 표본이 독립적으로 표집되었는가?

분산분석의 귀무가설, 대립가설
- 귀무가설 : 각 집단간의 평균은 동일하다.
- 대립가설 : 하나의 집단은 평균이 다르다.

총 제곱합 = 처리제곱합 + 오차제곱합으로 나눌 수 있다.
- 처리제곱합 : 처리 평균값, 전체평균값 차이 제곱의 합  
- 오차제곱합 : 자료값, 처리 평균값 차이 제곱합


#### Remark. 사후분석 : Tukey HSD
분산분석의 결과에 따라 어떤 집단이 유의미한 차이를 가지고 있는지 보는 분석법이다.